# -*- coding: utf-8 -*-
"""Automate-Ferdinan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1COIFrabW5y4fiMuOjwBq-j6Sew3kTF5p
"""

import pandas as pd

def hapus_outlier_iqr(df, kolom):
    Q1 = df[kolom].quantile(0.25)
    Q3 = df[kolom].quantile(0.75)
    IQR = Q3 - Q1
    batas_bawah = Q1 - 1.5 * IQR
    batas_atas = Q3 + 1.5 * IQR
    return df[(df[kolom] >= batas_bawah) & (df[kolom] <= batas_atas)]

def preprocess_data(path_csv):
    # Load data
    df = pd.read_csv(path_csv)

    # Hilangkan missing value
    df = df.dropna()

    # Hilangkan duplikat
    df = df.drop_duplicates()

    # Hilangkan data pada kolom SkinThickness > 0
    df = df[df['SkinThickness'] > 0]

    # Hapus outlier kolom numerik
    df = hapus_outlier_iqr(df, "Pregnancies",	"Glucose",	"BloodPressure",	"SkinThickness",	"Insulin",	"BMI",	"DiabetesPedigreeFunction", "Age")

    # Reset index agar rapi
    df = df.reset_index(drop=True)

    return df