name: Preprocess Dataset

on:
  push:
    paths:
      - 'Preprocessing/automate_ferdinan.py'
      - 'Preprocessing/Eksperimen_Ferdinan.ipynb'
      - 'Healthcare-Diabetes_preprocessing.csv'
      - 'Healthcare-Diabetes_raw.csv'
      - 'requirements.txt'
  workflow_dispatch:

jobs: 
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Jalankan preprocessing
        run: |
          python automate_ferdinan.py
